package multihost

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// Deployment builds the node binary for every host platform, transfers it
// with a generated start script, and starts, stops, and kills nodes through
// the executor. Only those two files are ever transferred; source never
// leaves this machine and the hosts do not need Go.
type Deployment struct {
	Inv       *Inventory
	Ex        Executor
	Scratch   string // local directory for built binaries and generated scripts
	BuildTags string // empty for the normal build; set for the planted-fault build
	RepoRoot  string

	binaries map[string]string // "goos/goarch" -> local binary path
	pids     map[uint64]int    // node id -> pid this driver started
}

// NewDeployment prepares a deployment; Scratch must exist or be creatable.
func NewDeployment(inv *Inventory, ex Executor, scratch, repoRoot, buildTags string) (*Deployment, error) {
	if err := os.MkdirAll(scratch, 0o755); err != nil {
		return nil, err
	}
	return &Deployment{
		Inv:       inv,
		Ex:        ex,
		Scratch:   scratch,
		RepoRoot:  repoRoot,
		BuildTags: buildTags,
		binaries:  map[string]string{},
		pids:      map[uint64]int{},
	}, nil
}

// Pids returns the process ids this driver started, by node id. Nothing else
// is ever signalled.
func (d *Deployment) Pids() map[uint64]int {
	out := map[uint64]int{}
	for id, pid := range d.pids {
		out[id] = pid
	}
	return out
}

// Build cross-compiles quorumlogd once per distinct host platform.
func (d *Deployment) Build(ctx context.Context) error {
	for _, h := range d.Inv.Hosts {
		target := h.BuildOS() + "/" + h.BuildArch()
		if _, ok := d.binaries[target]; ok {
			continue
		}
		name := fmt.Sprintf("quorumlogd-%s-%s", h.BuildOS(), h.BuildArch())
		if d.BuildTags != "" {
			name += "-" + strings.ReplaceAll(d.BuildTags, ",", "-")
		}
		out := filepath.Join(d.Scratch, name)
		args := []string{"build"}
		if d.BuildTags != "" {
			args = append(args, "-tags", d.BuildTags)
		}
		args = append(args, "-o", out, "./cmd/quorumlogd")
		cmd := exec.CommandContext(ctx, "go", args...)
		cmd.Dir = d.RepoRoot
		cmd.Env = append(os.Environ(), "GOOS="+h.BuildOS(), "GOARCH="+h.BuildArch())
		if combined, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("build %s: %w: %s", target, err, strings.TrimSpace(string(combined)))
		}
		d.binaries[target] = out
	}
	return nil
}

// BinaryFor returns the local path of the binary built for a host.
func (d *Deployment) BinaryFor(h Host) (string, error) {
	path, ok := d.binaries[h.BuildOS()+"/"+h.BuildArch()]
	if !ok {
		return "", fmt.Errorf("no binary built for %s/%s", h.BuildOS(), h.BuildArch())
	}
	return path, nil
}

// startScript is the only script transferred to a host. It starts the node
// detached, records its pid, and fails loudly if the process is already gone.
func (d *Deployment) startScript(h Host) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by qlmultihost. Starts one quorum-log node on this host.\n")
	b.WriteString("set -eu\n")
	fmt.Fprintf(&b, "DATA_DIR=%s\n", h.DataDir)
	b.WriteString("mkdir -p \"$DATA_DIR\"\n")
	b.WriteString("cd \"$DATA_DIR\"\n")
	b.WriteString("rm -f node.pid\n")
	fmt.Fprintf(&b, "nohup ./quorumlogd -id %d -listen %s -data \"$DATA_DIR\" -peers %s -chaos-listen %s >>node.log 2>&1 &\n",
		h.ID, h.ListenAddr(), ShellQuote(d.Inv.PeersFlag()), h.ChaosListenAddr())
	b.WriteString("echo $! >node.pid\n")
	b.WriteString("sleep 1\n")
	b.WriteString("PID=$(cat node.pid)\n")
	b.WriteString("kill -0 \"$PID\" 2>/dev/null || { echo \"node exited during startup; see $DATA_DIR/node.log\" >&2; tail -5 node.log >&2; exit 1; }\n")
	b.WriteString("echo \"$PID\"\n")
	return b.String()
}

// Deploy creates the data directory and transfers the binary and the start
// script. Transfer scope: those two files only.
func (d *Deployment) Deploy(ctx context.Context, h Host) error {
	bin, err := d.BinaryFor(h)
	if err != nil {
		return err
	}
	if _, err := d.Ex.Run(ctx, h, "mkdir -p "+h.DataDir); err != nil {
		return err
	}
	if err := d.Ex.Copy(ctx, h, bin, h.BinaryPath()); err != nil {
		return err
	}
	if _, err := d.Ex.Run(ctx, h, "chmod +x "+h.BinaryPath()); err != nil {
		return err
	}
	local := filepath.Join(d.Scratch, fmt.Sprintf("start-n%d.sh", h.ID))
	if err := os.WriteFile(local, []byte(d.startScript(h)), 0o755); err != nil {
		return err
	}
	if err := d.Ex.Copy(ctx, h, local, h.StartScriptPath()); err != nil {
		return err
	}
	_, err = d.Ex.Run(ctx, h, "chmod +x "+h.StartScriptPath())
	return err
}

// Start runs the start script and records the pid it reports.
func (d *Deployment) Start(ctx context.Context, h Host) (int, error) {
	out, err := d.Ex.Run(ctx, h, "sh "+h.StartScriptPath())
	if err != nil {
		return 0, err
	}
	pid, err := lastIntLine(out)
	if err != nil {
		return 0, fmt.Errorf("host %s: cannot read pid from start output %q: %w", h.Target(), strings.TrimSpace(out), err)
	}
	d.pids[h.ID] = pid
	return pid, nil
}

// StartAll deploys nothing new; it starts every node and waits for readiness.
func (d *Deployment) StartAll(ctx context.Context) error {
	for _, h := range d.Inv.Hosts {
		if _, err := d.Start(ctx, h); err != nil {
			return err
		}
	}
	return d.WaitReady(ctx, d.Inv.Hosts, 30*time.Second)
}

// signalScript signals only a pid this driver started, and only when that
// pid is still a quorumlogd process. Nothing else on the host is touched.
func signalScript(h Host, signal string) string {
	var b strings.Builder
	b.WriteString("set -eu\n")
	fmt.Fprintf(&b, "PIDFILE=%s\n", h.PidPath())
	b.WriteString("[ -f \"$PIDFILE\" ] || { echo \"no pid file\" >&2; exit 1; }\n")
	b.WriteString("PID=$(cat \"$PIDFILE\")\n")
	b.WriteString("CMD=$(ps -p \"$PID\" -o command= 2>/dev/null || true)\n")
	b.WriteString("case \"$CMD\" in\n")
	b.WriteString("  *quorumlogd*)\n")
	fmt.Fprintf(&b, "    kill -%s \"$PID\"\n", signal)
	b.WriteString("    echo \"signalled $PID\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("  \"\")\n")
	b.WriteString("    echo \"pid $PID already gone\"\n")
	b.WriteString("    ;;\n")
	b.WriteString("  *)\n")
	b.WriteString("    echo \"pid $PID is not a quorumlogd process; refusing to signal\" >&2\n")
	b.WriteString("    exit 1\n")
	b.WriteString("    ;;\n")
	b.WriteString("esac\n")
	return b.String()
}

// Kill sends SIGKILL to the node (the leader-failure fault).
func (d *Deployment) Kill(ctx context.Context, h Host) error {
	_, err := d.Ex.Run(ctx, h, signalScript(h, "9"))
	return err
}

// Stop sends SIGTERM and waits for the process to disappear, then escalates.
func (d *Deployment) Stop(ctx context.Context, h Host) error {
	if _, err := d.Ex.Run(ctx, h, signalScript(h, "TERM")); err != nil {
		return err
	}
	deadline := time.Now().Add(10 * time.Second)
	for time.Now().Before(deadline) {
		out, err := d.Ex.Run(ctx, h, fmt.Sprintf("ps -p $(cat %s) -o command= 2>/dev/null || true", h.PidPath()))
		if err == nil && !strings.Contains(out, "quorumlogd") {
			return nil
		}
		time.Sleep(100 * time.Millisecond)
	}
	return d.Kill(ctx, h)
}

// StopAll stops every node this driver started.
func (d *Deployment) StopAll(ctx context.Context) []error {
	var errs []error
	for _, h := range d.Inv.Hosts {
		if err := d.Stop(ctx, h); err != nil {
			errs = append(errs, fmt.Errorf("stop node %d: %w", h.ID, err))
		}
	}
	return errs
}

// WaitReady polls /status on each host until every one answers.
func (d *Deployment) WaitReady(ctx context.Context, hosts []Host, timeout time.Duration) error {
	client := &http.Client{Timeout: 2 * time.Second}
	deadline := time.Now().Add(timeout)
	for {
		pending := ""
		for _, h := range hosts {
			if !statusOK(ctx, client, h) {
				pending = h.Target()
				break
			}
		}
		if pending == "" {
			return nil
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("node on %s did not become ready within %s", pending, timeout)
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(100 * time.Millisecond):
		}
	}
}

func statusOK(ctx context.Context, client *http.Client, h Host) bool {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, h.RaftURL()+"/status", nil)
	if err != nil {
		return false
	}
	resp, err := client.Do(req)
	if err != nil {
		return false
	}
	resp.Body.Close()
	return resp.StatusCode == http.StatusOK
}

// TailLog returns the last lines of a node log, for failure diagnosis.
func (d *Deployment) TailLog(ctx context.Context, h Host, lines int) string {
	out, err := d.Ex.Run(ctx, h, fmt.Sprintf("tail -%d %s 2>/dev/null || true", lines, h.LogPath()))
	if err != nil {
		return ""
	}
	return out
}

func lastIntLine(out string) (int, error) {
	fields := strings.Fields(out)
	for i := len(fields) - 1; i >= 0; i-- {
		if n, err := strconv.Atoi(strings.TrimSpace(fields[i])); err == nil {
			return n, nil
		}
	}
	return 0, fmt.Errorf("no integer in output")
}
